"""notification sale_id and sale_nearby type

Revision ID: 4d7078914457
Revises: b0135d2a2526
Create Date: 2026-07-22 17:09:54.902831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d7078914457'
down_revision: Union[str, Sequence[str], None] = 'b0135d2a2526'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # enum 값 추가는 트랜잭션 밖에서(autocommit) — PG 제약 회피.
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE notification_type ADD VALUE IF NOT EXISTS 'SALE_NEARBY'")
    op.add_column('notifications', sa.Column('sale_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_notifications_sale_id'), 'notifications', ['sale_id'], unique=False)
    op.create_foreign_key(
        'fk_notifications_sale', 'notifications', 'sales', ['sale_id'], ['id']
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_notifications_sale', 'notifications', type_='foreignkey')
    op.drop_index(op.f('ix_notifications_sale_id'), table_name='notifications')
    op.drop_column('notifications', 'sale_id')
    # ### end Alembic commands ###
