"""unique owner_id on stores

Revision ID: b0135d2a2526
Revises: 91f2072e2598
Create Date: 2026-07-22 16:14:02.492755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0135d2a2526'
down_revision: Union[str, Sequence[str], None] = '91f2072e2598'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stores_owner_id'), table_name='stores')
    op.create_index(op.f('ix_stores_owner_id'), 'stores', ['owner_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stores_owner_id'), table_name='stores')
    op.create_index(op.f('ix_stores_owner_id'), 'stores', ['owner_id'], unique=False)
    # ### end Alembic commands ###
