STORE_NOT_FOUND = "매장을 찾을 수 없습니다"
SALE_NOT_FOUND = "마감세일을 찾을 수 없습니다"
MARKET_NOT_FOUND = "전통시장을 찾을 수 없습니다"
UNKNOWN_CATEGORY = "존재하지 않는 업종입니다"
UNKNOWN_UNIT = "존재하지 않는 단위입니다"
INVALID_SALE_PRICE = "할인가는 정상가보다 낮아야 합니다"
